---
# v2ray
v2ray_port: 40001
# get random uuid from https://www.uuidgenerator.net/
v2ray_client_id: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30326465653836383337363834353062663038623335636164343466663831373337633630363137
          3862313265383534623064316338323530666261313635320a633730303839373533326262316638
          37373363643135386464363636623962653065373363323837396137646630373864333962626230
          6636303063396531320a386630613366373135656461613036336634333133303536373332303830
          36396231626333383732663863623036373661623066303233353837333231663734333338613638
          6333326362613163323462363665656466333731353833356365
v2ray_alter_id: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66626664353462346539656433353839356164323066316139643635643935653836343531363637
          3032646162636634663363613339373237653361646630370a643265633430363933353939363133
          33373461323464623861623862666465353534383239316361643861316636376538343035626565
          6434633563636236380a393932303963396138323339636532653131373430643761376164386137
          6261

tls_shunt_proxy_enabled: false
# the domain name is only used when tls_shunt_proxy_enabled is true
domain_name: 
# cloudflare
cloudflare_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65623166363638666263363263393063363563653062346636616563636261303265356433386465
          3830303534383031336439386238653762316230336537630a626463313037376232356661336334
          36613834396434323635353034373666343235636536303338393334623030306465626532343134
          3164366261313031620a363664326632316561376536323434303136386238393437616563353838
          37336236383139393762333137353436656233353630336339346434623931626137343337663532
          6436303531386235613239373933663630356562326432393432
